/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Col: typeof import('./components/ToolBar/_components/col.vue')['default']
    Component: typeof import('./components/AddSubTaskButton/component.vue')['default']
    Filter: typeof import('./components/ToolBar/_components/filter.vue')['default']
    Item: typeof import('./components/DataList/_components/WaterFall/_components/item.vue')['default']
    Layout: typeof import('./components/ToolBar/_components/layout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectionSheet: typeof import('./components/FooterBar/_components/SelectionSheet.vue')['default']
    Share: typeof import('./components/ToolBar/_components/share.vue')['default']
    Sort: typeof import('./components/ToolBar/_components/sort.vue')['default']
  }
}
